---
- name: Install prerequisite package
  apt:
    name: "{{ docker_prereq_packages }}"
    update_cache: true

- name: Add Docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify gpg key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    update_cache: true

- name: install required pip modules
  pip:
    name: "{{ docker_pip_modules }}"
